# Archivo: webserv.conf

server {
    listen 8080;                        # Puerto obligatorio [3]
    host 127.0.0.1;                     # Host obligatorio [3]
    server_name miservidor.com;         # Nombre del servidor (opcional pero útil)

    # Página de error por defecto
    error_page 404 /error_pages/404.html;  # [3]
    error_page 500 /error_pages/500.html;

    # Límite de tamaño del cuerpo del cliente (para uploads)
    client_max_body_size 1024;          # Bytes (o 1M, según decidas parsear) [3]

    # Ruta raíz / (Default)
    location /casa/ {
        root ./www/html;                # Directorio donde están los archivos [3]
        allow_methods GET POST DELETE;  # Métodos permitidos [3]
        autoindex on;                   # Listado de directorios activado [3]
        index index.html;               # Archivo por defecto si es un directorio [3]
        location /user {

        }

    }

    # Ruta para subir archivos
    location /upload {
        root ./www/uploads;
        allow_methods POST;             # Aquí solo dejamos subir, no borrar ni leer
        upload_path ./www/uploads;      # Directorio de destino para uploads [3]
    }

    # Ruta para redirigir (Bonus/Feature)
    location /antiguo {
        return 301 /nuevo;              # Redirección HTTP [3]
    }

    # Configuración para CGI (scripts)
    location *.php {
        root ./www/scripts;
        cgi_pass ./cgi-bin/php-cgi;     # Ejecutable que procesará el script [4]
    }
}

# Segundo servidor en otro puerto (Virtual Host)
server {
    listen 9090;
    host 127.0.0.1;
    server_name admin.local;

    location / {
        root ./www/admin;
        allow_methods GET;
    }
}
